<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authorize\Module'                                    => __DIR__ . '/Module.php',
    'Authorize\Controller\Plugin\IsAllowed'               => __DIR__ . '/src/Authorize/Controller/Plugin/IsAllowed.php',
    'Authorize\Guard\Controller'                          => __DIR__ . '/src/Authorize/Guard/Controller.php',
    'Authorize\Guard\ControllerFactory'                   => __DIR__ . '/src/Authorize/Guard/ControllerFactory.php',
    'Authorize\Permission\Acl'                            => __DIR__ . '/src/Authorize/Permission/Acl.php',
    'Authorize\Service\Authorize'                         => __DIR__ . '/src/Authorize/Service/Authorize.php',
    'Authorize\Service\AuthorizeFactory'                  => __DIR__ . '/src/Authorize/Service/AuthorizeFactory.php',
    'Authorize\View\Strategy\UnauthorizedStrategy'        => __DIR__ . '/src/Authorize/View/Strategy/UnauthorizedStrategy.php',
    'Authorize\View\Strategy\UnauthorizedStrategyFactory' => __DIR__ . '/src/Authorize/View/Strategy/UnauthorizedStrategyFactory.php',
);
