<?php
	$this->headTitle($this->escapeHtml($this->translate("Đặt lại mật khẩu")));
?>
<div class="main-header">
	<h2><?= $this->translate('Đặt lại mật khẩu')?></h2>
	<em></em>
</div>
<div id="getPassword">
	<?php if($this->errorMessage){?>
	<div class="alert alert-danger alert-dismissable"><?= $this->errorMessage?></div>
	<?php }?>
	<?php if($this->successMessage){?>
	<div class="alert alert-success">
		<?= $this->successMessage?>
		<br/>
		Bấm vào <a href="/user/signin">đây</a> để đăng nhập vào hệ thống
	</div>

	<?php return;}?>
	<?php
	echo $this->partial('partial/formInput', array('form' => $this->form));
	?>

</div>
<style>
#getPassword .control-label{
	padding-top: 0;
}
</style>