

<ul class="breadcrumb">
    <li><a href="/admin"><i class="fa fa-home"></i></a></li>
    <li><a href="/admin/subject/index">Danh sách người dùng</a></li>
</ul>
<?php 

if ($this->flashMessenger()->hasMessages()) {

    echo '<div class="alert alert-warning">';

    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }

    echo '</div>';
}

?>
<div id='page-idea-contact'>
    <?php
    $this->headTitle($this->escapeHtml($this->translate("Danh sách người dùng")));
    echo '<div class="filterContainer">';
    echo $this->partial('partial/formFilter', [
        'form' => $this->form
    ]);
    echo '</div>';

    echo '</div>';

    $dg = new \Admin\DataGrid\User\User([
        'dataSource' => $this->paginator
    ]);
    echo $this->partial('partial/dataGrid', [
        'dataGrid' => $dg,
        'title' => $this->translate("Danh sách người dùng"),
    ]);
    $this->headScript()->appendFile(
            '/js/bootstrap-switch.min.js', 'text/javascript'
    );
    $this->headLink()->appendStylesheet('/css/bootstrap-switch.min.css');
    ?>

    <!-- Dialog bootstrap -->
    <div id="alertModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Thông báo</h4>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type='button' class='btn btn-default reload' data-dismiss='modal'>Đóng</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Button trigger modal -->
   
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Thay đổi quyền user</h4>
      </div>
         <form method="post" action="/admin/user/changerole">
      <div class="modal-body">
         
              <input type="hidden"  id="modal-id" name="id" value="">
              <div class="form-group">
                  <label>Email</label>
                  <input class="form-control" disabled id="modal-email">
              </div>
              <div class="form-group">
                  <label>Quyền user</label>
                  <select class="form-control" name="role" id="modal-role">
                      <option value="200">User</option>
                      <option value="5">Mentor</option>
                  </select>
              </div>
              <div class="form-group">
                  <label>Link Facebook</label>
                  <input class="form-control"  id="modal-face" name="facebook">
              </div>
              
         
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
              </form>
    </div>
  </div>
</div>
   
    <?php $this->headScript()->captureStart() ?>
    $.fn.bootstrapSwitch.defaults.onText = 'Active';
    $.fn.bootstrapSwitch.defaults.offText = 'Disable';
    $("[name='my-checkbox']").bootstrapSwitch();

    function setMentor(id){
        var user=$('#change-role-'+id);
        $("#modal-id").val(id);
        $("#modal-email").val(user.data("email"));
        $("#modal-role").val(user.data("role"));
        $("#modal-face").val(user.data("facebook"));
        $('#myModal').modal();
    }
    function changeActive(id) {
       
    var status = $('#switch-change' + id).bootstrapSwitch('state') ? 1 : 0;
    //        alert(status);
   // console.log("/admin/ajax/chinh-sua-quyen-{{$old['id']}}-" + id + "-" + status + ".html");
    $.ajax({
    url: "/admin/user/change?id="+id+"&active="+status,
    type: "GET",
    success: function (data) {
  //  alert(data);
    if (data) {
    alert(data);
    }
    },
    error: function () {
    alert("failure");
    }
    });
    }

    <?php $this->headScript()->captureEnd() ?>