<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Subject\Module'                        => __DIR__ . '/Module.php',
    'Subject\Controller\SubjectController' => __DIR__ . '/src/Subject/Controller/SubjectController.php',
    'SubjectTest\Framework\TestCase'        => __DIR__ . '/tests/Subject/Framework/TestCase.php',
    'SubjectTest\SampleTest'                => __DIR__ . '/tests/Subject/SampleTest.php',
);
