<?php
$this->headTitle($this->escapeHtml($this->translate("Phân quyền cho doanh nghiệp")));
$this->headScript()->appendFile('/min/f=/tp/v1/js/system/feature/company.js');
echo '<div class="filterContainer">';
echo $this->partial('partial/formFilter', ['form' => $this->form]);
echo '</div>';
if($this->errorMsg){
	echo '<div class="error">'.$this->errorMsg.'</div>';
	return;
}
if(!$this->features || !count($this->features)){
	echo '<div class="messages-feature">'.$this->translate('Doanh nghiệp này hiện chưa được phân quyền và đang sử dụng các quyền mặc định của hệ thống').'</div>';
}
$dg = new \System\DataGrid\System\Company(array(
	'options' => array(
		'features' => $this->features,
		'mcaList' => $this->mcaList,
		'compareFeatures' => $this->compareFeatures,
		'compareTitle' => $this->compareTitle,
		'companyId' => $this->companyId
	)
));
echo $this->partial('partial/dataGrid', [
	'dataGrid' => $dg,
	'title' => $this->translate("Phân quyền cho doanh nghiệp"),

]);
if($this->compareTitle){
	echo '<input id="btnSaveFeatures" class="btn btn-primary button-bottom" type="button" value="Lưu" >';
}
echo '<input id="btnDeletesFeatures" class="btn btn-warning button-bottom" type="button" value="Trở về mặc định" >';
?>

<style>
.messages-feature{
	text-align: center;
	color: red;
}
.button-bottom{
	display: inline-block;
	margin-right: 10px;
}
.search_area{
	position: fixed;
	top:50px;
	right: 0px;
	z-index: 12;
}
.search_area .togger_searchbox{
	font-size: 20px;
	color: #FFA500;
	float: left;
	cursor: pointer;
}
.search_area .search_box{
	width: 305px;
	height: 80px;
	float: left;
}
.search_area .search_box .search_box_content{
	background: #fff;
	border: 1px solid red;
	border-radius :2px;
	padding: 10px 5px;
}
.search_area .name_search{
	width: 240px;
	display: inline-block;
}
.search_area .search_module{
	display: inline-block;
	vertical-align: top;
}
table tr.found{
	background: #FCF5DC;
}
#overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: #000;
    filter:alpha(opacity=50);
    -moz-opacity:0.5;
    -khtml-opacity: 0.5;
    opacity: 0.5;
    z-index: 10000;
}
</style>
<div class="search_area">
	<a class="togger_searchbox">
		<i class="fa fa-chevron-circle-left "></i>
	</a>
	<div class="search_box hide">
		<div class="search_box_content">
			<div>
				<input type="text" class="name_search form-control" size="40" placeholder="/module/controller/action"/>
				<a class="btn btn-sm btn-warning search_module"><i class="fa fa-search icon"></i></a>
			</div>
		</div>
	</div>
</div>
<div id="errorDialog"  style="display: none;" title="Lỗi trong quá trình thực hiện"></div>
<script>
var companyId = '<?= $this->companyId?:0?>';
var lbClose = '<?= $this->translate('Đóng')?>';
var statusActive = '<?= \System\Model\Action::STATUS_ACTIVE?>';
var statusInactive = '<?= \System\Model\Action::STATUS_INACTIVE?>';
</script>