<?php
$this->headTitle($this->escapeHtml($this->translate("Danh sách action")));
$this->headScript()->appendFile('/min/f=/tp/v1/js/system/feature/mca.js');

$dg = new \System\DataGrid\Mca(array(
	'dataSource' => $this->dataSource
));
echo $this->partial('partial/dataGrid', [
	'dataGrid' => $dg,
	'title' => $this->translate("Danh sách mca"),
]);
$action = new \System\Model\Action();
?>
<style>
table .statusSelect, table .displaySelect{
	position: relative;
}
table ul.statusOptions, table ul.displayOptions{
	background: none repeat scroll 0 0 white;
    border: 1px solid #ddd;
    left: 50%;
    list-style: none outside none;
    margin-left: 10px;
    padding: 0;
    position: absolute;
    text-align: center;
    top: 0;
    width: 180px;
}
table ul.statusOptions li, table ul.displayOptions li{
	line-height: 25px;
    margin: 3px 0;
    padding-left: 10px;
    text-align: left;
    width: 100%;
	cursor: pointer;
}
table ul.statusOptions li:hover, table ul.displayOptions li:hover{
	background: #FCFBDE;
}
#dependenceDialog .description{
	font-size: 10px;
}
#dependenceDialog input[type="text"]{
	padding: 2px;
	width: 360px;
	display: inline-block;
}
#dependenceDialog .tag{
	margin-top: 6px;
	padding: 2px 4px;
	font-size: 12px;
	border: 1px solid #fff;
	border-radius: 2px;
}
#dependenceDialog .tag a{
	cursor: pointer;
}
#dependenceDialog .tagLink{
	margin-left: 8px;
}
.search_area{
	position: fixed;
	top:50px;
	right: 0px;
	z-index: 12;
}
.search_area .togger_searchbox{
	font-size: 20px;
	color: #FFA500;
	float: left;
	cursor: pointer;
}
.search_area .search_box{
	width: 305px;
	height: 80px;
	float: left;
}
.search_area .search_box .search_box_content{
	background: #fff;
	border: 1px solid red;
	border-radius :2px;
	padding: 10px 5px;
}
.search_area .name_search{
	width: 240px;
	display: inline-block;
}
.search_area .search_module{
	display: inline-block;
	vertical-align: top;
}
table tr.found{
	background: #FCF5DC;
}

</style>
<div class="search_area">
	<a class="togger_searchbox">
		<i class="fa fa-chevron-circle-left "></i>
	</a>
	<div class="search_box hide">
		<div class="search_box_content">
			<div>
				<input type="text" class="name_search form-control" size="40" placeholder="/module/controller/action"/>
				<a class="btn btn-sm btn-warning search_module"><i class="fa fa-search icon"></i></a>
			</div>
		</div>
	</div>
</div>
<div id="errorDialog"  style="display: none;" title="Lỗi trong quá trình thực hiện"></div>
<div id='dependenceDialog' style="display: none; z-index: 1;" title='<?= $this->translate('Nhập các action phụ thuộc')?>'>
	<div class="line_input line_name">
	<input type="hidden" class="actionId"/>
	<input type="text" size="40" class="linkDependence form-control"/>&nbsp;&nbsp;
	<button class="btn btn-primary btn-sm btn-ajax createDependence" type="button">
		<i class="fa fa-plus"></i>
		<span>Tạo</span>
	</button>
	</div>
	<div><i class="description">Nhập action phụ thuộc có dạng: /module/controller/action</i></div>
	<div class="tagsDependence">
		<div class="tagloading" style="margin:auto;text-align: center; font-size: 30px"><i class="fa fa-repeat fa-spin"></i></div>
	</div>
</div>
<script>
var lbClose = 'Đóng';
var lbAccept = "<?= $this->translate('Đồng ý')?>";
var statusActive = '<?= $action::STATUS_ACTIVE?>';
var statusInactive = '<?= $action::STATUS_INACTIVE?>';
var statusNames = {
	<?= $action::STATUS_ACTIVE?> :	'<?= $action->getStatusName($action::STATUS_ACTIVE)?>',
	<?= $action::STATUS_INACTIVE?> :	'<?= $action->getStatusName($action::STATUS_INACTIVE)?>',
};
var displayActive = '<?= $action::DISPLAY_ACTIVE?>';
var displayInactive = '<?= $action::DISPLAY_INACTIVE?>';
var displayNames = {
	<?= $action::DISPLAY_ACTIVE?> :	'<?= $action->getDisplayName($action::DISPLAY_ACTIVE)?>',
	<?= $action::DISPLAY_INACTIVE?> :	'<?= $action->getDisplayName($action::DISPLAY_INACTIVE)?>',
};
</script>