<?php $this->headScript()->appendFile('/tp/v1/js/admin/expert/add.js') ?>
<ul class="breadcrumb">
    <li><a href="/admin/subject"><i class="fa fa-home"></i></a></li>
    <li class="active">Sửa mentor</li>
</ul>
<style>
    .bootstrap-tagsinput {
        display: block;
    }

    .bootstrap-tagsinput .tag {
        display: inline-block;
        margin-bottom: 2px;
        margin-right: 2px;
    }
</style>
<div id='page-idea-add'>
    <?php
    $this->headTitle ( $this->escapeHtml ( $this->translate ( "Sửa mentor" ) ) );
    ?>
    <div class="main-header">
        <h2><?= $this->translate('Thêm mentor') ?></h2>
        <em>Các trường có dấu * là bắt buộc phải nhập</em>
    </div>
    <?= $this->partial('partial/my-form-input', array('form' => $this->form)); ?>

</div>