<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Website\Module'                  => __DIR__ . '/Module.php',
    'Website\Service\Template'        => __DIR__ . '/src/Website/Service/Template.php',
    'Website\Service\TemplateFactory' => __DIR__ . '/src/Website/Service/TemplateFactory.php',
);
