<div style="color:#505050;font-family:Arial;font-size:14px;line-height:150%;text-align:left">
    <h3>
        Chào mừng bạn đến với <span class="il">Funix</span>!
    </h3>
    You are one step away from completing your account registration.
    <br>
    <br>
    <span class="il">Codementor</span> provides instant 1:1 help for software development.  Please reply to this email or contact us at <a href="mailto:support@codementor.io" target="_blank">support@<span class="il">codementor</span>.io</a> with any questions or suggestions as you use the site.
    <br>
    <br>
    Please confirm your account through the link below:
    <br>
    <br>
    <table border="0" cellpadding="15" cellspacing="0" style="background-color:#336699;border:0;border-radius:3px;color:#ffffff;font-family:Arial;font-size:15px;font-weight:bold;letter-spacing:-.5px;line-height:100%;text-align:center;text-decoration:none;border-collapse:separate">
        <tbody><tr>
            <td style="border-collapse:collapse" valign="middle">
                <div style="color:#505050;font-family:Arial;font-size:14px;line-height:150%;text-align:left">
                    <a href="<?=$this->activeLink?>" style="color:#ffffff;font-family:Arial;font-size:15px;font-weight:bold;letter-spacing:-.5px;line-height:100%;text-align:center;text-decoration:none" target="_blank">
                        Confirm my
                        account
                    </a>
                </div>
            </td>
        </tr>
        </tbody></table>
    <br>
    <br>
    Sincerely,
    <br>
    <br>
    <b>The <span class="il">Codementor</span> Team</b>
</div>