<table border="0" cellpadding="0" cellspacing="0" style="border:1px solid #dddddd;background-color:#ffffff" width="600">
    <tbody>
    <tr>
        <td align="center" style="border-collapse:collapse" valign="top">

            <table border="0" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-bottom:0" width="600">
                <tbody><tr>
                    <td style="border-collapse:collapse;color:#202020;font-family:Arial;font-size:34px;font-weight:bold;line-height:100%;padding:0;text-align:center;vertical-align:middle">

                        <img src="https://ci4.googleusercontent.com/proxy/DqJiZnXVB4KkjyLMElcpVTcNS2SlLUNTC93x784QlxwPwMYnAsdmjgAj49qgHhj_HZd0qQ2dECKjsGFDgAvIZkjaL7Gu2veX=s0-d-e1-ft#http://www.codementor.io/assets/icon_bar_600px.png" style="max-width:600px;border:0;min-height:auto;line-height:100%;outline:none;text-decoration:none" class="CToWUd">

                    </td>
                </tr>
                </tbody></table>

        </td>
    </tr>
    <tr>
        <td align="center" style="border-collapse:collapse" valign="top">

            <table border="0" cellpadding="0" cellspacing="0" width="600">
                <tbody><tr>
                    <td style="border-collapse:collapse" valign="top">

                        <table border="0" cellpadding="20" cellspacing="0" width="100%">
                            <tbody><tr>
                                <td style="border-collapse:collapse;background-color:#ffffff" valign="top">
                                    <?=$this->content?>
                                </td>
                            </tr>
                            </tbody></table>


                    </td>
                </tr>
                </tbody></table>

        </td>
    </tr>
    <tr>
        <td align="center" style="border-collapse:collapse" valign="top">

            <table border="0" cellpadding="10" cellspacing="0" style="background-color:#ffffff;border-top:0" width="600">
                <tbody><tr>
                    <td style="border-collapse:collapse" valign="top">

                        <table border="0" cellpadding="10" cellspacing="0" width="100%">
                            <tbody><tr>
                                <td style="border-collapse:collapse" valign="top">
                                    <div style="color:#707070;font-family:Arial;font-size:12px;line-height:125%;text-align:center">
                                        <em>Copyright © 2015 <span class="il">Codementor</span>, All rights reserved.</em>
                                        <br>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td style="border-collapse:collapse;background-color:#ffffff;border:0" valign="middle">
                                    <div style="color:#707070;font-family:Arial;font-size:12px;line-height:125%;text-align:center">
                                        &nbsp;
                                        <a href="http://sendgrid.codementor.io/wf/click?upn=ud4YzC9prX2VNeOFM-2F5MtMXoJ-2FSZxicp0Rr7chCxi8A-3D_KfC5ICiNcFV0R5u8ttTBpPnpqOyii08UtOZ4bX9GHgTSGS2qN1MOnsIuzL9DycIpiKpjpLME0kwE1kge9bejqXZeU6hJ8FUI5ATU7SkRRxXyvNAVVGmnQcMgT8wMwO81mzEjmshDEI545J1E-2FJ-2FgntgyjQAyp2Pg-2B-2FzQcY2LGBZhAWlnSPqOBvLfCMI94e88V5MZ2prlEwuF7LXrfvGRwg-3D-3D" style="color:#336699;font-weight:normal;text-decoration:underline" target="_blank">
                                            Visit <span class="il">Codementor</span>
                                        </a>
                                        |
                                        <a href="mailto:support@codementor.io" style="color:#336699;font-weight:normal;text-decoration:underline" target="_blank">Contact Us</a>
                                        &nbsp;
                                    </div>
                                </td>
                            </tr>
                            </tbody></table>

                    </td>
                </tr>
                </tbody></table>

        </td>
    </tr>
    </tbody></table>