<?php
$this->headLink()->prependStylesheet('/css/home/index.css');
$this->headScript()->appendFile('/tp/v1/js/home/index.js');
$form = $this->form;
?>
    <div check-time-zone=''></div>

    <div class='homepage' >
        <div class='landing index'>
            <div class="with-request-form">
                <div class="headerBlock">
                    <div class="hero-unit">
                        <center>
                            <?php include(TEMPLATES_PATH.'\html\index.html')?>
                        </center>
                    </div>
                    <div class="customizeContainer">
                        <div class="row-fluid request-form-wrapper">
                            <div class="span10 offset1">
                                <form class="request-form" action="/home/search" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">
                                    <?php
                                        echo $this->formelement($form->get('search')->setAttributes([
                                            'placeholder'   =>  'Tìm kiếm sự giúp đỡ ở đây',
                                            'required'  =>  'required'
                                        ]));
                                    ?>
                                    <button class="btn btn-red" type="submit">
                                        <span>Giúp đỡ</span>
                                    </button>
                                </form>
                            </div>
                        </div>
<!--                        <div class="row-fluid action-links" style="display:none;">-->
<!--                            <div class="span12 text-center">-->
<!--                                <a class="sign-up-link actionLink" data-target="#signup-modal" data-toggle="modal" href="#" role="button">-->
<!--                                    Sign up to learn more-->
<!--                                </a>-->
<!--                            </div>-->
<!--                        </div>-->
                        <div class="row-fluid signup-button text-center">
                            <div class="span12">
                                <a class="btn btn-red signup" >
                                    Sign Up Now
                                </a>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span12 video-block">
                                <a data-theVideo="https://www.youtube.com/embed/hZb05RC_vzE"  class="video" data-toggle="modal" data-target="#myModal">
                                    Video giới thiệu
                                    <i class="play-video">
                                        <i class="fa fa-play"></i>
                                    </i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class='solution'>
                <div class='customizeContainer'>
                    <div class='row-fluid'>
                        <div class='span3'>
                            <div class='column'>
                                <div class='subtitle'>
                                    <img class='image' src='http://funix.edu.vn/wp-content/uploads/2015/09/21-150x150.png'>

                                </div>
                                <p class='description'>
                                    Tự quyết định tiến độ học của mình, học nhanh, đi làm sớm, có thu nhập sớm trang trải học phí.
                                </p>
                            </div>
                        </div>
                        <div class='span3'>
                            <div class='column'>
                                <div class='subtitle'>
                                    <img class='image' src='http://funix.edu.vn/wp-content/uploads/2015/09/11-150x150.png'>

                                </div>
                                <p class='description'>
                                    Được học từ bài giảng của các trường Đại học CNTT, các chuyên gia hàng đầu thế giới.
                                </p>
                            </div>
                        </div>
                        <div class='span3'>
                            <div class='column'>
                                <div class='subtitle'>
                                    <img class='image' src='http://funix.edu.vn/wp-content/uploads/2015/09/31-150x150.png'>

                                </div>
                                <p class='description'>
                                    Được tiếp xúc với những chuyên gia hàng đầu đang làm việc trong ngành CNTT tại Việt nam.
                                </p>
                            </div>
                        </div>
                        <div class='span3'>
                            <div class='column'>
                                <div class='subtitle'>
                                    <img class='image' src='http://funix.edu.vn/wp-content/uploads/2015/09/41-150x150.png'>

                                </div>
                                <p class='description'>
                                    Bằng Kỹ sư CNTT được Bộ giáo dục công nhận, xét mức lương Đại học, có thể học lên Thạc sĩ, Tiến sĩ.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class='blockDecoration' id='experts'>
            <div class='customizeContainer'>
                <div class='row-fluid'>
                    <div class='span12'>
                        <h2 class='blockHeader'>
                            HỌC CÙNG CHUYÊN GIA (MENTOR), HỌ LÀ AI?
                        </h2>
                    </div>
                </div>
                <div class='row-fluid'>
                    <div class='span10 offset1'>
                        <center>
                            <p class='marketing-byline'>
                                Là các chuyên gia công nghệ hàng đầu Việt Nam, người trực tiếp “chỉ đường” cho sinh viên trong quá trình học, đồng thời là nhà tuyển dụng sinh viên trong tương lai
                            </p>
                        </center>
                    </div>
                </div>
                <br>

                </div>
                <br>

                <div class='hide-mobile'>
                    <div class='row-fluid'>
                            <div class='span2'>
                                <center>
                                    <div class='mentorModule'>
                                        <img alt='Steve Klabnik' class='mentorImg'
                                             src='http://funix.edu.vn/wp-content/uploads/2015/10/376933c-200x200.jpg'>

                                        <div class='userTitle'>
                                            Mentor Nguyễn Thành Lâm
                                        </div>
                                        <p class='description'>
                                            Nguyên Tổng giám đốc FPT Software
                                        </p>
                                    </div>
                                </center>
                            </div>
                            <div class='span2'>
                                <center>
                                    <div class='mentorModule'>
                                        <img alt='Martijn Pieters' class='mentorImg'
                                             src='http://funix.edu.vn/wp-content/uploads/2015/10/144f251-200x200.jpg'>

                                        <div class='userTitle'>
                                            Mentor Hoàng Tô
                                        </div>
                                        <p class='description'>
                                            Chủ tịch kiêm Tổng giám đốc Tinh Vân Group
                                        </p>
                                    </div>
                                </center>
                            </div>
                            <div class='span2'>
                                <center>
                                    <div class='mentorModule'>
                                        <img alt='Rebecca Murphey' class='mentorImg'
                                             src='http://funix.edu.vn/wp-content/uploads/2015/10/Hoang-Giang-%E1%BA%A2nh11-200x200.jpg'>

                                        <div class='userTitle'>
                                            Mentor Hoàng Giang
                                        </div>
                                        <p class='description'>
                                            Phó giám đốc Trung tâm sản phẩm ứng dụng – Tổng công ty Viettel Telecom
                                        </p>
                                    </div>
                                </center>
                            </div>
                            <div class='span2'>
                                <center>
                                    <div class='mentorModule'>
                                        <img alt='Arlo Carreon' class='mentorImg'
                                             src='http://funix.edu.vn/wp-content/uploads/2015/10/2ae154b1-200x200.jpg'>

                                        <div class='userTitle'>
                                            Mentor Tô Hải Sơn
                                        </div>
                                        <p class='description'>
                                            Giám đốc Công nghệ Công ty cổ phần NTQ Solution
                                        </p>
                                    </div>
                                </center>
                            </div>
                        <div class='span2'>
                            <center>
                                <div class='mentorModule'>
                                    <img alt='Michael Hartl' class='mentorImg'
                                         src='http://funix.edu.vn/wp-content/uploads/2015/10/tueth-%E1%BA%A3nh1-200x200.jpg'>

                                    <div class='userTitle'>
                                        Mentor Trần Hữu Tuệ
                                    </div>
                                    <p class='description'>
                                        Hiện đang là Quản lý Đơn vị kinh doanh số 5 FPT Software
                                    </p>
                                </div>
                            </center>
                        </div>
                        <div class='span2'>
                            <center>
                                <div class='mentorModule'>
                                    <img alt='Michael Hartl' class='mentorImg'
                                         src='http://funix.edu.vn/wp-content/uploads/2015/10/anhtvv_20151-200x200.jpg'>

                                    <div class='userTitle'>
                                        Mentor Trần Vũ Việt Anh
                                    </div>
                                    <p class='description'>
                                        Hiện đang là Giám đốc Công ty công nghệ Bắc Hà
                                    </p>
                                </div>
                            </center>
                        </div>
                        </div>
                </div>
            </div>

                <div class='row-fluid'>
                    <div class='span12'>
                        <center>
                            <br>
                                <h2>HỌC GÌ Ở FUNIX</h2>
                            </br>
                        </center>
                        <div class='row-fluid'>
                            <div class='span10 offset1'>
                                <center>
                                    <p class='marketing-byline' style="line-height: 3em">
                                        Học liệu từ các trường Đại học, nguồn học liệu hàng đầu thế giới, được chọn lọc, chứng minh tính tối ưu, phù hợp với ngành CNTT,

                                        bởi hội đồng khoa học gồm đại diện 3 bên: Ngành Công nghiệp, Trường Đại học và Nhà khoa học
                                    </p>
                                </center>
                            </div>
                        </div>
                        <div class = 'row-fluid'>
                            <div class="span4">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/09/images2-200x200.png">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/09/download-11.png">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/09/download1-200x200.png">
                                        </center>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/09/coursera-logo-200x200.png">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/09/photo-200x200.png">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/09/codecademy-logo-200x200.png">
                                        </center>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="row-fluid">
                            <center>
                                <p class='marketing-byline' style="line-height: 3em">
                                    Chương trình học gồm 8 kì, mỗi kì 4 tháng.

                                    Sau mỗi kì sinh viên sẽ nhận được 1 Chứng chỉ, chứng nhận có thể làm được việc tương ứng, được công nhận bởi bên thứ 3 là một công ty lớn trong ngành CNTT của Việt Nam.

                                    Hoàn thành 8 kì, sinh viên sẽ trở thành Kỹ sư CNTT, nhận bằng Đại học được Bộ giáo dục công nhận
                                </p>
                            </center>
                        </div>
                        <div class = 'row-fluid'>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/111.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/21.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/31.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/41.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class = 'row-fluid'>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/51.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/61.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/71.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="topicBlock">
                                    <a class="link">
                                        <center>
                                            <img alt="Coding" class="imgBlock" src="http://funix.edu.vn/wp-content/uploads/2015/10/81.jpg">
                                        </center>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    </div>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog" style="display: none">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Giới thiều về funix</h4>
            </div>
                <iframe width="853" height="480" src="" frameborder="0"></iframe>
        </div>

    </div>
</div>
<style>
    #myModal{
        width: 853px;
        height: 480px;
        margin-left: -442px;
    }
    #myModal .modal-header .close {
        color: #f0f6fb;
        margin-top: -6px;
    }
    .modal-header h4 {
        color: #ddd;
        margin: 0;
        line-height: 7px;
    }
</style>