<ul class="breadcrumb">
	<li><a href="/"><i class="fa fa-home"></i></a></li>
	<li><a href="/profile">Profile</a></li>
	<li class="active">Đổi mật khẩu</li>
</ul>
<div id='page-crm-contact-add'>
<?php
	$this->headTitle($this->escapeHtml($this->translate("Thêm dự án")));
	$this->headScript ()->appendFile ( '/tp/v1/js/user/profile/edit.js' );
	$message = $this->message;
?>
	<div class="main-header">
		<h2><?= $this->translate('Đổi mật khẩu')?></h2>
		<em>Các trường có dấu * là bắt buộc phải nhập</em>
	</div>
	<?= $this->partial('partial/formInput', array('form' => $this->form)); ?>
</div>
<input type="text" id ="message" style="display: none" value="<?= $message?>">