<?php
use Home\Model\DateBase;
use Home\Model\Consts;
$this->headScript()->appendFile('/min/f=/assets/js/dropzone.min.js');
$this->headscript()->appendFile('/min/f=/js/bootstrap-editable.min.js');
$this->headScript()->appendFile('/min/f=/assets/js/select2.min.js');
$this->headScript ()->appendFile ( '/min/f=/tp/v1/js/user/profile/city.js' );
$this->headScript ()->appendFile ( '/min/f=/tp/v1/js/user/profile/jquery.maskedinput.min.js' );
$this->headScript()->appendFile('/min/f=/assets/js/bootstrap-progressbar.js');
$this->headScript ()->appendFile ( '/min/f=/tp/v1/js/user/profile/index.js?01' );
$this->headLink()->appendStylesheet('/css/dropzone.css');

$user = $this->user;
?>
<!-- main -->
<style>
.select2-chosen{
	padding-right: 10px !important;
}
.editable-input {
	width:200px;
	padding-right: 10px;
}
#uploadFile {
	height: 80px;
	border: 2px dashed #ccc;
	border-radius: 5px;
}

#uploadFile .uploadDescription {
	margin: auto;
	margin-top: 12px;
	text-align: center;
	cursor: pointer;
}

#previewsContainer .item {
	min-height: 150px;
	display: block;
	border: 1px solid #ccc;
}

#previewsContainer .item .item-preview {
	height: 100px;
	border-bottom: 1px solid #ccc;
	text-align: center;
}

#previewsContainer .item .item-info {
	padding: 5px 3px;
	text-align: center;
}

#previewsContainer .item .name {
	word-wrap: break-word;
}
</style>
<div class="content">
	<div class="main-header">
		<h2>Thông tin cá nhân</h2>
		<em>Trang thông tin người dùng</em>
	</div>

	<div class="main-content">
		<!-- NAV TABS -->
		<ul class="nav nav-tabs">
<!-- 			<li class="active"><a data-toggle="tab" href="#profile-tab"><i -->
<!-- 					class="fa fa-user"></i> Profile</a></li> -->
<!-- 			<li class=""><a data-toggle="tab" href="#activity-tab"><i -->
<!-- 					class="fa fa-rss"></i> Recent Activity</a></li> -->
<!-- 			<li class=""><a data-toggle="tab" href="#settings-tab"><i -->
<!-- 					class="fa fa-gear"></i> Settings</a></li> -->
		</ul>
		<!-- END NAV TABS -->

		<div class="tab-content profile-page">
			<!-- PROFILE TAB CONTENT -->
			<div id="profile-tab" class="tab-pane profile active">
				<div class="row">
					<div class="col-md-3">
						<div class="user-info-left">
							<img alt="Không có ảnh đại diện" src="<?= \Home\Service\Uri::getViewPath($user)?>">
							<h2>
								<?php echo	$user->getUserName(); ?> <i class="fa fa-circle green-font online-icon"></i><sup
									class="sr-only">online</sup>
							</h2>
<!-- 							<div class="contact"> -->
<!-- 								<a class="btn btn-block btn-custom-primary" href="#"><i -->
<!-- 									class="fa fa-envelope-o"></i> Send Message</a> <a -->
<!-- 									class="btn btn-block btn-custom-secondary" href="#"><i -->
<!-- 									class="fa fa-book"></i> Add To Contact</a> -->
<!-- 								<ul class="list-inline social"> -->
<!-- 									<li><a title="Facebook" href="#"><i -->
<!-- 											class="fa fa-facebook-square"></i></a></li> -->
<!-- 									<li><a title="Twitter" href="#"><i class="fa fa-twitter-square"></i></a></li> -->
<!-- 									<li><a title="Google Plus" href="#"><i -->
<!-- 											class="fa fa-google-plus-square"></i></a></li> -->
<!-- 								</ul> -->
<!-- 							</div> -->
						</div>
					</div>
					<div class="col-md-9">
						<div class="user-info-right">
							<div class="basic-info">
								<h3>
									<i class="fa fa-square"></i> Thông tin cơ bản
								</h3>
								<div style="float: right; margin-bottom: 10px">
            						<button id="enable" class="btn btn-default">sửa thông tin</button>
            					</div>
								<input type="text" value="<?= $user->getId()?>" style="display: none" id="userId">
								<p class="data-row">
									<span class="data-name">Tên đầy đủ</span>
									<a href="#" id="fullname" data-name="fullName" data-type="text" data-placement="right" data-title="Nhập tên họ"><?=$user->getFullName()?></a>
								</p>
								<p class="data-row">
									<span class="data-name">Ngày sinh</span>
									<a href="#" id="birthdate" data-name="birthdate" data-type="combodate" data-template="D / MM / YYYY" data-viewformat="DD/MM/YYYY" data-placement="right" data-title="Enter ngày sinh"><?php
									 if($user->getBirthdate()){
											echo DateBase::toDisplayDate($user->getBirthdate());
														}else {
															echo 'Empty';
														}
									 ?></a>
								</p>
								<p class="data-row">
                                
									<span class="data-name">Giới tính</span>
									<a href="#" id="gender" data-name ="gender" data-type="select" data-placement="right" data-title="Chọn giới tính"><?=Consts::getGenderName($user->getGender())?></a>
								</p>
								<p class="data-row">
									<span class="data-name">Đăng nhập lần cuối</span> <span
										class="data-value"><?= $user->getLastAccess() ?></span>
								</p>
								<p class="data-row">
									<span class="data-name">Ngày đăng kí</span> <span
										class="data-value"><?php
										if($user->getcreatedDate()){
											echo DateBase::toDisplayDate($user->getcreatedDate());
										}else {
											echo 'Empty';
										}
										?></span>
								</p>
							</div>
							<div class="contact_info">
								<h3>
									<i class="fa fa-square"></i> Liên hệ
								</h3>
								<p class="data-row">
									<span class="data-name">Thành Phố</span>
									<a href="#" id="cityId" data-type="select2" data-value="<?=$user->getCityId()?>" data-placement="right" data-title="Chọn tỉnh/thành phố"><?=$user->getCity()->getName() ?></a>
									<input id="cityIdhidden" type="text" value="<?=$user->getCityId()?>" hidden>
									<input id="cityIdhidden1" type="text" value="" hidden>
								</p>
								<p class="data-row">
									<span class="data-name">Quận huyện</span>
									<a href="#" id="districtId" data-type="select2" data-placement="right" data-title="Chọn quận/huyện"><?=$user->getDistrict()->getName()?></a>
								</p>
								<p class="data-row">
									<span class="data-name">Địa chỉ</span>
									<a href="#" id="address" data-name="address" data-type="text" data-placement="right" data-title="Nhập địa chỉ"><?=$user->getAddress()?></a>
								</p>
								<p class="data-row">
									<span class="data-name">Điện thoại</span>
									<a href="#" id="mobile" data-type="text" data-placement="right" data-title="Nhập số điện thoại"><?=$user->getMobile()?></a>
								</p>
								<p class="data-row">
									<span class="data-name">Email</span>
									<a href="#" id="email" data-type="email" data-placement="right" data-title="Nhập Email"><?=$user->getEmail()?></a>
								</p>
<!-- 													<p class="data-row"> -->
<!-- 									<span class="data-name">Email</span> -->
<!-- 									<a href="#" id="avatar" data-type="file" data-placement="right" data-title="Enter email"> -->
<!-- 									</a> -->
<!-- 								</p> -->
								<p class="data-row">
			<!-- Upload file drop zone -->
		<div class="col-md-12">
			<fieldset>
				<legend>Upload avatar</legend>
				<div class="form-group">
					<div class="col-md-12">
						<form action="/media/manage/upload" method="post"
							enctype="multipart/form-data" id="uploadFile"
							style="height: 80px; overflow: hidden;">
							<div class="uploadDescription dz-clickable dz-message">
								<span class="fontsize-130 text-muted"><i class="fa fa-upload"></i>
									<b>Click vào để upload</b></span><br /> <span
									class="fonsize-100 text-muted">(Chỉ nhận file <i>'jpg', 'jpeg',
										'gif', 'png'</i> và dung lượng nhỏ hơn 1Mb)
								</span>
							</div>
						</form>
					</div>
					<div class="col-md-12" id="previewsContainer"></div>
					<br />

				</div>
			</fieldset>
		</div>

		<div id="preview-template" style="display: none;">
			<div class="dz-preview dz-file-preview col-md-3 status-uploading">
				<div class="item">
					<div class="item-preview">
						<div class="dz-image">
							<img data-dz-thumbnail="">
						</div>
					</div>
					<div class="item-info">
						<div class="dz-details">
							<div class="size">
								<div class="dz-size">
									<span data-dz-size=""></span>
								</div>
							</div>
							<div class="name fontsize-85">
								<div class="dz-filename">
									<span data-dz-name=""></span>
								</div>
							</div>
						</div>
						<div class="progress progress-striped active" role="progressbar"
							aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
							<div class="progress-bar progress-bar-success" style="width: 0%;"
								data-dz-uploadprogress></div>
						</div>

						<div class="dz-error-message">
							<span data-dz-errormessage=""></span>
						</div>
						<div class="dz-success-mark">
							<i class="fa-fa-check color-green"></i>
						</div>
						<div class="dz-error-mark">
							<i class="fa-fa-times color-red"></i>
						</div>
					</div>
				</div>
			</div>
		</div>

<!-- End upload file -->
						</p>
							<div class="about">
								<h3>
									<i class="fa fa-square"></i> Về tôi
								</h3>

							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- END PROFILE TAB CONTENT -->

			<!-- ACTIVITY TAB CONTENT -->
<!-- 			<div id="activity-tab" class="tab-pane activity"> -->
<!-- 				<ul class="list-unstyled activity-list"> -->
<!-- 					<li><i class="fa fa-shopping-cart activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> commented on <a href="#">Special Deal -->
<!-- 								2013</a> <span class="timestamp">12 minutes ago</span> -->
<!-- 						</p></li> -->
<!-- 					<li><i class="fa fa-pencil activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> posted <a href="#">a new blog post</a> <span -->
<!-- 								class="timestamp">4 hours ago</span> -->
<!-- 						</p></li> -->
<!-- 					<li><i class="fa fa-user activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> edited his profile <span -->
<!-- 								class="timestamp">11 hours ago</span> -->
<!-- 						</p></li> -->
<!-- 					<li><i class="fa fa-pencil activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> has added review on <a href="#">jQuery -->
<!-- 								Complete Guide</a> book <span class="timestamp">Yesterday</span> -->
<!-- 						</p></li> -->
<!-- 					<li><i class="fa fa-thumbs-up activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> liked <a href="#">a post</a> <span -->
<!-- 								class="timestamp">December 12</span> -->
<!-- 						</p></li> -->
<!-- 					<li><i class="fa fa-tasks activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> has completed one task <span -->
<!-- 								class="timestamp">December 11</span> -->
<!-- 						</p></li> -->
<!-- 					<li><i class="fa fa-picture-o activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> uploaded <a href="#">new photos</a> <span -->
<!-- 								class="timestamp">December 5</span> -->
<!-- 						</p></li> -->
<!-- 					<li><i class="fa fa-credit-card activity-icon pull-left"></i> -->
<!-- 						<p> -->
<!-- 							<a href="#">Jonathan</a> has updated his credit card info <span -->
<!-- 								class="timestamp">September 28</span> -->
<!-- 						</p></li> -->

<!-- 				</ul> -->
<!-- 				<p class="text-center more"> -->
<!-- 					<a class="btn btn-custom-primary" href="#">View more <i -->
<!-- 						class="fa fa-long-arrow-right"></i></a> -->
<!-- 				</p> -->
<!-- 			</div> -->
			<!-- END ACTIVITY TAB CONTENT -->

			<!-- SETTINGS TAB CONTENT -->
<!-- 			<div id="settings-tab" class="tab-pane settings"> -->
<!-- 				<form role="form" class="form-horizontal"> -->
<!-- 					<fieldset> -->
<!-- 						<h3> -->
<!-- 							<i class="fa fa-square"></i> Change Password -->
<!-- 						</h3> -->
<!-- 						<div class="form-group"> -->
<!-- 							<label class="col-sm-3 control-label" for="old-password">Old -->
<!-- 								Password</label> -->
<!-- 							<div class="col-sm-4"> -->
<!-- 								<input type="password" class="form-control" name="old-password" -->
<!-- 									id="old-password"> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- 						<hr> -->
<!-- 						<div class="form-group"> -->
<!-- 							<label class="col-sm-3 control-label" for="password">New Password</label> -->
<!-- 							<div class="col-sm-4"> -->
<!-- 								<input type="password" class="form-control" name="password" -->
<!-- 									id="password"> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- 						<div class="form-group"> -->
<!-- 							<label class="col-sm-3 control-label" for="password2">Repeat -->
<!-- 								Password</label> -->
<!-- 							<div class="col-sm-4"> -->
<!-- 								<input type="password" class="form-control" name="password2" -->
<!-- 									id="password2"> -->
<!-- 							</div> -->
<!-- 						</div> -->
<!-- 					</fieldset> -->

<!-- 				</form> -->

<!-- 				<p class="text-center"> -->
<!-- 					<a class="btn btn-custom-primary" href="#"><i -->
<!-- 						class="fa fa-floppy-o"></i> Save Changes</a> -->
<!-- 				</p> -->

			</div>
			<!-- END SETTINGS TAB CONTENT -->
		</div>

	</div>
	<!-- /main-content -->
</div>
<!-- /main -->
<!-- Dialog bootstrap -->
<div id="myModal" class="modal fade">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Thông báo</h4>
			</div>
			<div class="modal-body"></div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>
