<?php
	$this->headTitle($this->translate('Đổi đường đãn file thông báo'));
?>
<input type='hidden' id="redirectUri" value="<?= $this->redirectUri?>" />
<input type='hidden' id="defaultRedirectUri" value="<?= $this->defaultRedirectUri?>" />
<b>Đã chuyển: </b><?= $this->totalFile?> file<br/>
<script type="text/javascript">
	setTimeout(function(){
		if(document.getElementById("redirectUri").value != "") {
			window.location = document.getElementById("redirectUri").value;
		} else {
			alert('Đã update xong');
			windown.location = '/work/task/index';
		}
	}, 500);
</script>
<i><b class='lnk'>Đã update được [<?= $this->page .' / '. $this->totalPages ?>] trang</b></i><br><br>