<?php
	$this->headTitle($this->translate('Lấy tài sản từ office'));
	$paginator = $this->paginator;
	/*@var $paginator \Zend\Paginator\Paginator */
?>
<input type='hidden' id="redirectUri" value="<?= $this->redirectUri?>" />
<input type='hidden' id="defaultRedirectUri" value="<?= $this->defaultRedirectUri?>" />
Số asset_item tạo mới: <?= $this->totalAssetItem?><br/>
Số asset tạo mới: <?= $this->totalAsset?><br/>

<script type="text/javascript">
	setTimeout(function(){
		if(document.getElementById("redirectUri").value != "") {
			window.location = document.getElementById("redirectUri").value;
		} else if(document.getElementById("defaultRedirectUri").value != "") {
			setTimeout(function(){
				window.location = document.getElementById("defaultRedirectUri").value;
			}, 600000);
		}
	}, 500);
</script>
<a href="<?= $this->defaultRedirectUri?>" class='lnk'>Restart [<?= $paginator->getCurrentPageNumber() .' / '. $paginator->count() ?>]</a><br><br>