<?php ?>
<input type='hidden' id="redirectUri" value="<?= $this->redirectUri?>" />
<input type='hidden' id="defaultRedirectUri" value="<?= $this->defaultRedirectUri?>" />
<h4><?=$this->page?>/<?= $this->totalPages?></h4><br/>
<script type="text/javascript">
	setTimeout(function(){
		if(document.getElementById("redirectUri").value != "") {
			window.location = document.getElementById("redirectUri").value;
		} else if(document.getElementById("defaultRedirectUri").value != "") {
			setTimeout(function(){
				window.location = document.getElementById("defaultRedirectUri").value;
			}, 3600000);
		}
	}, 500);
</script>
<a href="<?= $this->defaultRedirectUri?>" class='lnk'>Restart</a><br><br>
