

<ul class="breadcrumb">
	<li><a href="/accounting"><i class="fa fa-home"></i></a></li>
	<li><a href="/accounting/expense/category">Danh sách khoản mục chi phí</a></li>
</ul>
<div id='page-idea-contact'>
    <?php
    			//$this->headScript ()->appendFile ( '/min/f=/tp/v1/js/accounting/expensive/del.js?02' );
				$this->headTitle ( $this->escapeHtml ( $this->translate ( "Khoản mục chi phí" ) ) );
				echo '<div class="filterContainer">';
				echo $this->partial ( 'partial/formFilter', [ 
						'form' => $this->form 
				] );
				echo '</div>';
					echo '</div>';
					$dg = new \Accounting\DataGrid\ExpenseCategory ( [ 
							'dataSource' => $this->expenseCategorys 
					] );
					if ($this->expenseCategorys ){
    					echo $this->partial ( 'partial/dataGrid', [ 
    							'dataGrid' => $dg,
    							'title' => $this->translate ( "Danh mục khoản mục chi phí" ),
    							'topButtons' => '<a href="/accounting/expense/addcategory" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Thêm khoản mục</a>' 
    					] );
					}
					else{
                        echo '<div class="alert alert-warning alert-dismissable">
                    	           <a href="" class="close">×</a>
                    	           <strong>Cảnh báo!</strong> Không có dữ liệu
                             </div>';
                    }
				?>

<!-- Dialog bootstrap -->
<div id="delModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title">Thông báo</h4>
			</div>
			<div class="modal-body">
			    <div class='alert alert-info alert-dismissable'>Xác nhận xóa tài khoản</div>
			</div>
			
			<div class="modal-footer">
			     <button type='button' class='btn btn-primary confirm'>Xác nhận</button>
			     <button type='button' class='btn btn-default' data-dismiss='modal'>Đóng</button>
			</div>
		</div>
	</div>
</div>
<div id="alertModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title">Thông báo</h4>
			</div>
			<div class="modal-body"></div>		
			<div class="modal-footer">
			     <button type='button' class='btn btn-default reload' data-dismiss='modal'>Đóng</button>
			</div>
		</div>
	</div>
</div>
