<ul class="breadcrumb">
	<li><a href="/accounting"><i class="fa fa-home"></i></a></li>
	<li><a href="/accounting/expense/category">Khoản mục chi phí</a></li>
	<li class="active">Sửa khoản mục</li>
</ul>
<div id='page-idea-edit'>
    <?php
            $this->headScript ()->appendFile ( '/min/f=/tp/v1/js/accounting/expense/addcategory.js?02' );
			$this->headTitle ( $this->escapeHtml ( $this->translate ( "Sửa khoản mục" ) ) );
				?>
    <div class="main-header">
		<h2><?= $this->translate('Sửa khoản mục chi phí') ?></h2>
		<em>Các trường có dấu * là bắt buộc phải nhập</em>
	</div>
    <?= $this->partial('partial/formInput', array('form' => $this->form)); ?>
</div>

